### ISSUE TITLE
Does not appear to render

### ISSUE THREAD

**Issue by ssdpress** [mastahyeti/Google-Docs-Markdown#5]
First of all, thank you for the awesome add-on.  If I can get this working properly this would be a huge improvement to a semi-repetitive task I need to perform.

I just installed and tested this and when I try to render it no longer seems to be able to render properly.  I see one of the reviews also made this comment so I'm suspecting it isn't just me. For me it just seems to strip all of my formatting and line breaks and gives me just a set of text blocks.

I'm trying to start with something like this in a google doc:

**Header 1**

line 1: text
line 2: text

**Header 2**
- line 1
- line 2
  - indent 1
    - double indent 1
  - indent 2
- line 3

And I get this:

```
Header 1

line 1: text line 2: text

Header 2 line 1 line 2 indent 1 double indent 1 indent 2 line 3
```

I would expect to see:

```
**Header 1**

line 1: text
line 2: text

**Header 2**

* line 1
* line 2
   * indent 1
      * double indent 1
   * indent 2
* line 3
```

Thank you.

**Comment by btoews** [comment]
Hey @ssdpress. I think this tool might do the opposite of what you're looking for. This tool renders an HTML preview of markdown formatted text. It sounds like you're looking for something that converts rich text to Markdown. I'm closing this issue because I don't think it's a bug. Feel free to reopen it if I'm misunderstanding the problem.

**Comment by ssdpress** [comment]
Yep, I realized that later and thought I'd left a comment, but appears I didn't.  Thanks for looking at it.
